### ISSUE TITLE
New release version for python3 compatibilty

### ISSUE THREAD

**Issue by bpatel2107** [PSFCPlasmaTools/eqtools#10]
Is it possible to release a new version of this code that is compatible in python3?

We are developing a python library for gyrokinetics and would like to use your pfile reader. I imagine the A file reader may come in handy in the future

See below
https://github.com/pyro-kinetics/pyrokinetics/issues/166

**Comment by markchil** [comment]
I think we had gotten it pretty much Python 3-ready a couple years ago, just didn't package it up for a new pip release. I'll try to get some time to double-check and prepare a new release in the next few days.

Have you run into any specific bugs trying to run in Python 3, or is it just that you aren't able to get the latest version through pip?

**Comment by markchil** [comment]
Ok, I just published 1.4.0 to PyPI with the Python 3 compatibility updates. Note that I don't currently have access to an MDSplus server to test this with. Also note that I couldn't find good documentation on how to port the f2py/numpy.distutils stuff to the new pyproject.toml-based packaging, so that may be fragile. In particular, this will break in 3.12 when they remove distutils. I'm going to go ahead and close this issue. Please open a new issue if you have any problems with pip-installing the new version.
