### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by nicolavianello** [PSFCPlasmaTools/eqtools#8]
Hi, I'm wonder if you have plan to upgrade eqtools in order to make it python3 compatible. So far I've noticed there are some small issue due to print function but they should be relatively easy to solve. I don't yet go deeply into the code to see if there are other issues but I would like to know which are the plan, if any

**Comment by icfaust** [comment]
Hey Nicola,

Unfortunately, I would love to help out, but there are a lot of test cases on MDSplus datasystems that would need to be run to make sure that the code is both stable and bug-free for Python3 (I still have a rather massive use of 'xrange' in this code for example).  Since the three of us are no longer employed at fusion labs, data access for us is only going to be more and more difficult. I'll be honest, we haven't dealt with any MDSplus compatibility issues in ~2 years for this reason (may also be the reason why its been forked by others).  I would need to become re-acquainted with changes in MDSplus first.
